apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-model-service
  namespace: default
  title: Developer Model Service
  description: A vLLM and 3scale-based model service providing models for developer tools.
  tags: [genai, ibm-granite, vllm, llm, developer-model-service, authenticated, gateway]
  links:
    - url: https://model-service.apps.domain.com
      title: Access
    - url: https://ibm-granite-8b-code-instruct-vllm.apps.domain.com
      title: API URL
  annotations:
    backstage.io/techdocs-ref: dir:.    # <-- canonical form
spec:
  type: model-server
  owner: user:default/exampleuser
  lifecycle: production
  providesApis: [model-service-api]
  dependsOn:
    - resource:default/ibm-granite-8b-code-instruct
    - api:default/model-service-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ibm-granite-8b-code-instruct
  namespace: default
  title: IBM Granite Code Model
  annotations:
    backstage.io/techdocs-ref: dir:ibm-granite-8b-code-instruct
spec:
  type: ai-model
  owner: user:default/exampleuser
  lifecycle: production
  dependencyOf: [component:default/developer-model-service]
  providesApis: [model-service-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: model-service-api
  namespace: default
  title: Model Service API
spec:
  type: openapi
  owner: user:default/exampleuser
  lifecycle: production
  definition: |
    {"openapi":"3.1.0","info":{"title":"FastAPI","version":"0.1.0"}}
